using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyVersionAttribute("3.0.2")]
[assembly: AssemblyFileVersionAttribute("3.0.2")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2013-2015 Thinking-Home.RU")]
[assembly: AssemblyProductAttribute("ThinkingHome.Service")]

