using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyVersionAttribute("2.0.0.48")]
[assembly: AssemblyFileVersionAttribute("2.0.0.48")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2013-2015 Thinking-Home.RU")]
[assembly: AssemblyProductAttribute("ThinkingHome.Service")]

