//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThinkingHome.Plugins.Scripts.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ScriptsUiLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScriptsUiLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThinkingHome.Plugins.Scripts.Lang.ScriptsUiLang", typeof(ScriptsUiLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add script.
        /// </summary>
        internal static string Add_script {
            get {
                return ResourceManager.GetString("Add_script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add subscription.
        /// </summary>
        internal static string Add_subscription {
            get {
                return ResourceManager.GetString("Add_subscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the &quot;{0}&quot; script?.
        /// </summary>
        internal static string Delete_the_0_script {
            get {
                return ResourceManager.GetString("Delete_the_0_script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the subscription?
        ///- event: &quot;{0}&quot;
        ///- script: &quot;{1}&quot;.
        /// </summary>
        internal static string Delete_the_subscription_0_1 {
            get {
                return ResourceManager.GetString("Delete_the_subscription_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to detach.
        /// </summary>
        internal static string detach {
            get {
                return ResourceManager.GetString("detach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter script name.
        /// </summary>
        internal static string Enter_script_name {
            get {
                return ResourceManager.GetString("Enter_script_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        internal static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event handlers.
        /// </summary>
        internal static string Event_handlers {
            get {
                return ResourceManager.GetString("Event_handlers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute now.
        /// </summary>
        internal static string Execute_now {
            get {
                return ResourceManager.GetString("Execute_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit fullscreen.
        /// </summary>
        internal static string Exit_fullscreen {
            get {
                return ResourceManager.GetString("Exit_fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullscreen editing.
        /// </summary>
        internal static string Fullscreen_editing {
            get {
                return ResourceManager.GetString("Fullscreen_editing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to noname.
        /// </summary>
        internal static string noname {
            get {
                return ResourceManager.GetString("noname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script.
        /// </summary>
        internal static string Script {
            get {
                return ResourceManager.GetString("Script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scripts.
        /// </summary>
        internal static string Scripts {
            get {
                return ResourceManager.GetString("Scripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{0}&quot; script has been executed..
        /// </summary>
        internal static string The_0_script_has_been_executed {
            get {
                return ResourceManager.GetString("The_0_script_has_been_executed", resourceCulture);
            }
        }
    }
}
