//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThinkingHome.Plugins.Weather.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WeatherLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WeatherLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThinkingHome.Plugins.Weather.Lang.WeatherLang", typeof(WeatherLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add location.
        /// </summary>
        internal static string Add_location {
            get {
                return ResourceManager.GetString("Add_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API query.
        /// </summary>
        internal static string API_query {
            get {
                return ResourceManager.GetString("API_query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the location &quot;{0}&quot; and all location data?.
        /// </summary>
        internal static string Delete_the_location_0_and_all_location_data {
            get {
                return ResourceManager.GetString("Delete_the_location_0_and_all_location_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name.
        /// </summary>
        internal static string Display_name {
            get {
                return ResourceManager.GetString("Display_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to example: Moscow.
        /// </summary>
        internal static string example_Moscow {
            get {
                return ResourceManager.GetString("example_Moscow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to example: Moscow,ru.
        /// </summary>
        internal static string example_Moscow_ru {
            get {
                return ResourceManager.GetString("example_Moscow_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forecast.
        /// </summary>
        internal static string Forecast {
            get {
                return ResourceManager.GetString("Forecast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next day.
        /// </summary>
        internal static string Next_day {
            get {
                return ResourceManager.GetString("Next_day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update.
        /// </summary>
        internal static string update {
            get {
                return ResourceManager.GetString("update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather.
        /// </summary>
        internal static string Weather {
            get {
                return ResourceManager.GetString("Weather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather data is loaded from.
        /// </summary>
        internal static string Weather_data_is_loaded_from {
            get {
                return ResourceManager.GetString("Weather_data_is_loaded_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather locations.
        /// </summary>
        internal static string Weather_locations {
            get {
                return ResourceManager.GetString("Weather_locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather service API query.
        /// </summary>
        internal static string Weather_service_API_query {
            get {
                return ResourceManager.GetString("Weather_service_API_query", resourceCulture);
            }
        }
    }
}
