//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThinkingHome.Plugins.AlarmClock.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AlarmClockLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AlarmClockLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThinkingHome.Plugins.AlarmClock.Lang.AlarmClockLang", typeof(AlarmClockLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALARM!.
        /// </summary>
        public static string Alarm {
            get {
                return ResourceManager.GetString("Alarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarms.
        /// </summary>
        public static string Alarms {
            get {
                return ResourceManager.GetString("Alarms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded {0} alarm times.
        /// </summary>
        public static string Loaded_0_alarm_times {
            get {
                return ResourceManager.GetString("Loaded_0_alarm_times", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play sound.
        /// </summary>
        public static string Play_sound {
            get {
                return ResourceManager.GetString("Play_sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run alarm script: {0} ({1}).
        /// </summary>
        public static string Run_alarm_script_0_1 {
            get {
                return ResourceManager.GetString("Run_alarm_script_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run event handlers: {0} ({1}).
        /// </summary>
        public static string Run_event_handlers_0_1 {
            get {
                return ResourceManager.GetString("Run_event_handlers_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run subscribed scripts.
        /// </summary>
        public static string Run_subscribed_scripts {
            get {
                return ResourceManager.GetString("Run_subscribed_scripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop all sounds.
        /// </summary>
        public static string Stop_all_sounds {
            get {
                return ResourceManager.GetString("Stop_all_sounds", resourceCulture);
            }
        }
    }
}
